### ISSUE TITLE
1st実装へのコメント

### ISSUE THREAD

**Issue by ms2sato** [benrickken/file-viewer#1]
https://github.com/benrickken/file-viewer/tree/9db71465fb138a0f578edced6320696f0868a7bd
時点でのコミュニケーションポイント。PRではなかったのでコメント箇所に困ってここにしました。

実際に作成されたものを見て「ここは議論になりそうだな」と思う箇所を発掘して取り出しています。もしかしたらより良い設計があるかもしれないし、そのままの方が良いかもしれません。少なくとも私が設計レビューする際にコミュニケーションするだろうポイントを抜き出しました。その観点で会話しましょう（私の頭の中の正解を当てるゲームではないです）。

# FileViewerクラスの意義について
このクラスはシンプルにViewStrategyに委譲するだけのコードになっているので、特にFileViewerクラスが存在せず、ViewStrategyが共通のインターフェースを持ち、FileViewerFactory から返される実装もありえる。何か意図がある場合には知りたいです。

# FileViewerFactoryが受け取るべき情報について
https://github.com/benrickken/file-viewer/blob/9db71465fb138a0f578edced6320696f0868a7bd/routes/index.js#L25

この判断により、FileViewerを作成するのには「mimetypeだけが関与する」と決め打ちになったが、将来「特定のファイルサイズによっては表現を変えたい」「リクエストパラメータに何か指定すると表現が変わる」のような要件ができた時にFileViewerFactoryにも変更が加わりそうに感じる。もう少し大きめの情報を渡せると柔軟ではないだろうか（どこまで大きくするのかは議論がありそうだけども一旦出しておく）。

# displayHTML(path) について
pathを渡すのがこのタイミングである理由をコミュニケーションしたいですね。理由があったら聞いてみたいです。

**Comment by cmasad** [comment]
@ms2sato ありがとうございます！
> PRではなかったのでコメント箇所に困ってここにしました。

PRにすればよかったですね、すみません。

**Comment by benrickken** [comment]
@ms2sato ありがとうございます！
> PRではなかったのでコメント箇所に困ってここにしました。

PRにすればよかったですね、すみません。

**Comment by benrickken** [comment]
# FileViewerクラスの意義について
> このクラスはシンプルにViewStrategyに委譲するだけのコードになっているので、特にFileViewerクラスが存在せず、ViewStrategyが共通のインターフェースを持ち、FileViewerFactory から返される実装もありえる。何か意図がある場合には知りたいです。

確かにそうですね。思考の流れとして、
「今後対象ファイルの種類は増える」という要件から
→ Strategy, Decorator, Template Methodパターンあたりが良いかな？
→ 複数DecorateしたいことはなさそうなのでDecoratorパターンではなくて良さそう
→ 継承の階層は増えることがあるかも？Template Methodだと増えすぎたときに大変かも
→ アルゴリズムを実行時に選択することができるStrategyにしよう
という流れで、いつでも取り替えられるようにStrategyパターンにしていました。

そこから作っていく中で、生成するオブジェクトの種類の変更をファクトリの処理の中で動的に行いたいのでFactoryパターンでもあるのか？と思いFileViewerFactoryを作った結果FileViewerクラスの必要意義が見えにくくなった気がします。

**Comment by benrickken** [comment]
# FileViewerFactoryが受け取るべき情報について
> この判断により、FileViewerを作成するのには「mimetypeだけが関与する」と決め打ちになったが、将来「特定のファイルサイズによっては表現を変えたい」「リクエストパラメータに何か指定すると表現が変わる」のような要件ができた時にFileViewerFactoryにも変更が加わりそうに感じる。もう少し大きめの情報を渡せると柔軟ではないだろうか（どこまで大きくするのかは議論がありそうだけども一旦出しておく）。

これもおっしゃるとおりかなと思いました。fileOptionsみたいなobjectを渡せるようのが良いでしょうか。

**Comment by benrickken** [comment]
# displayHTML(path) について
> pathを渡すのがこのタイミングである理由をコミュニケーションしたいですね。理由があったら聞いてみたいです。

ここはあまり考えていなかったです、別の方法としては各ViewStrategyのプロパティとして持たせるようなイメージでしょうか？その場合一つ前のfileOptionsの話と絡めて、pathとかのファイル情報（`req.file`に入ってる諸々）を渡す形がいいかもと思いました。

**Comment by ms2sato** [comment]
@benrickken 

# FileViewerクラスの意義について

この件は書いてくださっている通りかなと思います。Strategyを導入した際にありがちなのですが「単純なポリモーフィズムで事足りた」というケースはよくあるので、一度書き上げた後にもう一度意義を確認できると良さそうですね！
Factoryにしたのはとても良かったと思います。このクラスに「どういう条件でどんなFileViewerを作り出すか」という判断が詰まっているイメージはわかりやすいです。

# FileViewerFactoryが受け取るべき情報について
ここは、2つの考え方がバッティングする場所だと思います。なので私も判断が難しいと感じます。

1. FileViewerFactoryはできる限り多くの情報を貰っておいた方が柔軟になる
2. FileViewerFactoryはモデル側にいるので、リクエストに関するオブジェクトをそのまま渡すことに抵抗がある

2を完全に無視してよければ最も多くの情報を持っているreqをそのまま渡してしまうのが最良なのですが、1がそれを邪魔するんですよね。私だと、req.file を第一引数で渡すのは確定として、あとは要件が増えたらオプションのobjectを第二引数として、reqから必要な情報が取り出せるように拡張しそうな気がします（ここは後からオプションobjectのインターフェースが変わっても大きな影響は無いので目を瞑る感じ）人によっては雑にreqをそのまま渡すのはやりそうですね。

# displayHTML(path) について
なるほど！ここは何か意図があれば聞いてみたかったのですが手癖的に書かれていた感じですね。ちょっと込み入った話になりそうなので水曜日に回させてください。
